### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [caronc/ha-ultrasync#1]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by caronc** [comment]
Thanks for your advice! :+1: I think i got the Actions in place, I just need to add the `ultrasync` branding and set it up so it can build a wheel.  Was going to tackle it later on this week as i got busy doing other things. 
![hacs-ultrasync-actions](https://user-images.githubusercontent.com/850374/101569947-6c0a5100-39a3-11eb-9427-24eb454688f5.png)

But I won't turn down any help/advice/pull requests you have all the same! Thank you! :slightly_smiling_face:  I'm off to bed now, but I'll take another stab at it tomorrow.

**Comment by KTibow** [comment]
Sounds good. I can get some automatic black/isort formatting added, and some flake8 too.
