### ISSUE TITLE
Provide a way to just disarm/arm a specific Area

### ISSUE THREAD

**Issue by caronc** [caronc/ha-ultrasync#10]
Currently the system arms/disarms the alarm in it's entirety (all Areas).  Provide a means of just targeting specific Areas.

**Comment by ndabar** [comment]
thanks for this great integration. I just discovered. 
I have included your "ultrasync_alarm.yaml" and the three buttons appear on my HA, however it seems they only show me the current status. Do I need to change something in your code in order to arm/disarm the alarm?

**Comment by caronc** [comment]
I'm out of town, but i will try to share my code with you for what i did when i get back.

**Comment by ndabar** [comment]
Thanks a mill caronc! I did few changes but still is just visual. Please let me know once you are back.

**Comment by ndabar** [comment]
I guess all is good now. Probably I messed up something in the configuration, I did few tests and they worked. Thanks again for creating this add-ons.

**Comment by caronc** [comment]
Glad you got it all going; i'll close the ticket off then 🚀
