### ISSUE TITLE
Lovelace UI grid placemant

### ISSUE THREAD

**Issue by mickeybyte** [caronc/ha-ultrasync#16]
Hi, 
It seems I'm unable to get your lovelace UI working on my system. I get the following output:
![image](https://user-images.githubusercontent.com/46132262/144741267-1f271adb-59a3-462e-af87-f1ef2e285bd3.png)
No matter what i try to change on the gridcol/gridrow values, I never get the layout it should be (3x2 state icon, 2 1x1 buttons for stay/away).
I installed the lovelace-layout-card and button-card through HACS (and modified the incorrect resource URLs to the correct ones).

Any idea what can be wrong? 

Thanks, 
Michiel.

**Comment by caronc** [comment]
Weird, off hand I can't spot the problem without actually seeing your yaml configuration; but if you base it off of [this](https://raw.githubusercontent.com/caronc/ha-ultrasync/main/ultrasync_alarm.yaml) as you said you already did, i'm not sure what would cause it not to work.

I documented the parts of the grid system the buttons appear for (same link) as part of inline comments... hence the main button on the left (occupying 2/3rds of the space):
![image](https://user-images.githubusercontent.com/850374/144753672-55f49312-eef1-4875-97aa-cd40b4a8ef96.png)

then each other button fitting in their place on the right:
![image](https://user-images.githubusercontent.com/850374/144753694-201e7fb9-aba2-417a-94d6-17c69f21d559.png)

and...
![image](https://user-images.githubusercontent.com/850374/144753708-fca85553-8fa6-4e1c-a61a-73ea01094e0b.png)


The rest of the entries are for styling/actions etc... but those are the core settings you need to get the layout you desire.

**Comment by mickeybyte** [comment]
I used the code from your link indeed, but the layout doesn't seem to work. I understand how it should work, it just doesn't. 
The only change I did that actually changes something in my view is when I change the second line "layout: grid" to "layout_type: grid". Then I get 3 equal icons underneath each other. So still not what it should be.
I've also been searching for documentation about the gridcol/row settings but I can't find anything about it. I only can find a link on the lovelace-layout-card github readme that points to [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/). However in their documentation there's no mention of gridcol or gridrow settings... 
I'm completely lost...

**Comment by phyco1991** [comment]
@mickeybyte I was able to get this to work by doing the following

Edit the dashboard
Edit the card
Use the arrow buttons to change the layout
![waterfox_2022-07-02_14-20-41](https://user-images.githubusercontent.com/14029065/176989249-27a5c51b-8dc3-4d92-9adb-ead0273baa30.png)

**Comment by mickeybyte** [comment]
@phyco1991,
Thanks for the update! I'll have a look at it, but currenlty that project is on low priority here due to other work.

**Comment by skatsavos** [comment]
Since the provided layout was not working very nice for my, i decided to create the following:

Installed Custom Features for Home Assistant Cards:
https://github.com/Nerwyn/service-call-tile-feature

Then i used the following yaml: 
`features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: sensor.ultrasync_ready_state
        options:
          - icon: mdi:shield-off-outline
            option: Disarmed
            tap_action:
              action: perform-action
              perform_action: ultrasync.disarm
              data: {}
              confirmation:
                text: Disarm the Alarm?
            type: button
            value_attribute: state
            styles: |-
              :host {
                --color: Orange;
                flex-basis: 100%;
              }
          - icon: mdi:shield-home-outline
            option: Armed Stay
            tap_action:
              action: perform-action
              perform_action: ultrasync.stay
              confirmation:
                text: Set alarm to Stay mode?
              data: {}
            type: button
            value_attribute: state
            styles: |-
              :host {
                --color: MediumSeaGreen;
                flex-basis: 100%;
              }
          - icon: mdi:shield-lock-outline
            option: Away
            tap_action:
              action: perform-action
              perform_action: ultrasync.away
              data: {}
              confirmation:
                text: Set alarm to Away mode?
            type: button
            value_attribute: state
            styles: |-
              :host {
                --color: SteelBlue;
                flex-basis: 100%;
              }
        value_attribute: state
        styles: ""
type: tile
entity: sensor.ultrasync_area1state
show_entity_picture: false
vertical: false
grid_options:
  columns: 12
  rows: 2
hide_state: false
state_content: state
tap_action:
  action: none
card_mod:
  style: |
    @keyframes blinker {
      0% { opacity: 1; }
      100% { opacity: 0.3; }
    }

    ha-card {
      {% if states('sensor.ultrasync_area1state') in ['Exit Delay 1'] %}
      animation: blinker 1s infinite alternate;
      {% endif %}
    }
`

Because i needed to match Not Ready and Ready states to one option i had also to modify the configuration.yaml and add:
`sensor:
  - platform: template
    sensors:
      ultrasync_ready_state:
        friendly_name: "UltraSync Ready State"
        value_template: >-
          {% if states('sensor.ultrasync_area1state') in ['Ready', 'Not Ready'] %}
            Disarmed
          {% else %}
            {{ states('sensor.ultrasync_area1state') }}
          {% endif %}`

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/adcc288c-7c12-4c72-984a-0c669b9464fe" />
