### ISSUE TITLE
Hills XR Pro Alarm

### ISSUE THREAD

**Issue by crook2108** [caronc/ha-ultrasync#17]
Hi, 

I love that someone has done this! I have installed Ultrasync Beta on my Home Assistant but I only have 6 entites, is that correct or should I see alot more. Not sure if this is compatible with the latest hills xr pro panel or if its just me.
![Screenshot (1)](https://user-images.githubusercontent.com/98072810/150283583-d3a460aa-7354-40cd-a272-4978940c2913.png)

**Comment by crook2108** [comment]
sorry for the dumb question but how where do I
![Screenshot (2)](https://user-images.githubusercontent.com/98072810/150291658-7097df30-644b-42e6-8185-b72b975e141f.png)
 create a service?

**Comment by caronc** [comment]
If it's working correctly, you should see the sensors you've set up.  As for setting up your own Automation. That's a bit tricky the first time. You need to open up your main home assistant configuration file and simply add the entry under there (reload Home Assistant to read the configuration).

I believe today Home Assistant is advanced enough that you can write your Automation directly into it through the Web page with Admin access.  It's more of a wizard.  But you can follow through and chose `time` when it asks you what you want it to trigger on, etc. (you can use the information above and populate the wizard itself).

This isn't the best answer (i realize this), but you're a bit outside of the scope of this small plugin :).

**Comment by crook2108** [comment]
Hi, 
Thanks for responding. Not sure if this is the correct way way to do it but I created a service to arm/stay/disarm alarm, then allowed services on HomeKit integration and now when I leave home it is arming automatically and disarming when I arrive home. It is exactly what I wanted to do, so thank you for creating this.
![Uploading DB4C9D75-DA19-4147-B9B2-3AC7067A648F.png…]()

**Comment by crook2108** [comment]
![9DFC0151-24CA-4FB0-B344-4A46C0C3925A](https://user-images.githubusercontent.com/98072810/150603640-23c325c3-c0f9-4714-b37f-cc0ffb31e53e.jpeg)

**Comment by crook2108** [comment]
![Uploading 6745927B-23FA-41DA-98E7-7D014F7D3C8E.png…]()

**Comment by crook2108** [comment]
I also figured out how to rename the zones and area. 👍

**Comment by caronc** [comment]
I'm really glad to see you figured it all out! Great job! :+1:

**Comment by crook2108** [comment]
I’ve created an automation now of a light is left on any any room that has a motion sensor for more than a minute and no motion is detected it will turn the light off in that particular room. The kids always leave every light on in the house so this will save me money in the long run. I have sent you a small token of my appreciation. Hopefully you receive it

**Comment by caronc** [comment]
Sorry to take so long to get back to you! Thank you so much for your contribution! It's incredibly kind of you!

I'll close this ticket off, but feel free to open a new or ask any questions you may have in another! 👍🙂
