### ISSUE TITLE
Bypass / Unbypass service not working

### ISSUE THREAD

**Issue by thanomichalis** [caronc/ha-ultrasync#23]
Hello, 

The bypass or unbypass zone service cannot run. From the logs, i get the following:

_**_This error originated from a custom integration.

Logger: ultrasync
Source: custom_components/ultrasync/__init__.py:115
Integration: UltraSync Alarm Panel Beta
First occurred: 1:05:41 PM (46 occurrences)
Last logged: 4:47:46 PM

Bypass not implemented for vendor comnav_**_

Any ideas?

Thank you in advance

**Comment by chatziko** [comment]
Hi, the bypass zone command was implemented by me, and initially supported only xGen8, since that's the only hardware I have. A [recent commit](https://github.com/caronc/ultrasync/commit/13a74026bebedd1e4f435c1f56b71c6ac55630a3) added ZeroWire  support (seems to have identical implementation so it was trivial).

You seem to have ComNav however, which judging from the other commands has a bit different implementation, so you'd need to add support for it in the [ultrasync](https://github.com/caronc/ultrasync) repo. It shouldn't be too hard, but you need to modify the code  and a little bit of reverse engineering to understand what command you need to send to the alarm. If you feel you have the skils and time to do it, start by understanding the code in that repo, and I can provide pointers if needed.

**Comment by flareman** [comment]
Hi, just wanted to chime in; I have created a Homebridge plugin for ComNav (Interlogix/Caddx/ComNav), basing my work on the original reverse engineering done by @caronc and porting the code to TypeScript, further adding several enhancements such as zone bypassing, output control and other ([project link](https://github.com/flareman/homebridge-caddx-interlogix)). For the bypass command on ComNav panels, the actual command needed is `http://alarm.panel.ip/user/zonefunction.cgi`, with the following arguments passed:

- `comm`: 82
- `data0`: the zone to be toggled, starting numbering from number 0

The web interface doesn't pass any other arguments to the CGI script, so I'm guessing that the only command that a zone can accept is toggling the bypass state, and therefore doesn't need any other kind of details.

I am not fluent in Python so I can't possibly try and submit a pull request, but maybe someone else could. All the best, and keep up the good work :)

**Comment by thanomichalis** [comment]
Hi again @chatziko , i think i found something but i do not know how to implemented.

In the main.py at line 538, i saw the payload for the ComNav for arm disarm to be like that:
             else:  # self.vendor is NX595EVendor.COMNAV

                payload.update({
                    'comm': 80,
                    'data0': 2,
                    'data1': 1 << (area - 1) % 8,
                })

So further down for the bypass/unbypass (which is empty for ComNav), i think we can use a similar to the other models but with comm and data0... something like that:

                payload.update({
                'comm': 82,
                'data0':  " here it is suppose to set the zone??? "
                 
Cause based on the comments of flareman above, i saw in the web interface that it passes the following when clicking the button to bypass/ubypass: 
<button type="button" class="bb bg-yel" onclick="newAJAXCommand('/user/zonefunction.cgi', zoneCGIresponse, false,'**comm=82**&amp;**data0**=1')"><div class="bi"></div>Bypass</button>
Where still the zones are starting from 0.

Is that of a help? if yes, where exactly should i paste it to test it? i cannot see the main.py in the HA file editor.

**Comment by chatziko** [comment]
The ultrasync integration has 2 parts:
- the "main logic" part is a python library responsible for actually communicating with the alarm. (repo: https://github.com/caronc/ultrasync)
- the "home assistant extension" is reponsible for connecting that library with HA (repo: https://github.com/caronc/ultrasync)

`main.py` belongs to the first, which unfortunately is installed __inside the homeassistant docker container__. I can give instructions about how to reach it, but it will be a real pain to try to debug this way.

What is __much easier__ to do is install the python library (https://github.com/caronc/ultrasync) in your PC, and use it to directly access the alarm (without the complexity of HA). Note: better use a different alarm account when connecting from your PC, to avoid messing with the one you configured in HA.

This way you will have `main.py` in your PC and it will be trivial to change it, try different params, add debug logs, etc. You can test the bypass command with:
```
ultrasync --bypass=1 --zone=1
```
and for removing the bypass:
```
ultrasync --bypass=0 --zone=1
```


When you finally have a working version, then you can try applying your modified `main.py` in the homeassistant container.

**Comment by thanomichalis** [comment]
Got it...!!!

we need just to update that part in the main.py:
        else:  # self.vendor is NX595EVendor.{COMNAV, ZEROWIRE, XGEN}
             logger.error(
             'Bypass not implemented for vendor {}'.format(self.vendor))
             return False

with that:
        else:  # self.vendor is NX595EVendor.{COMNAV, ZEROWIRE, XGEN}
            **payload.update({
                'comm': 82,
                'data0': zone - 1,
            })**
            # logger.error(
                # 'Bypass not implemented for vendor {}'.format(self.vendor))
            # return False

So how can i added into my HA?

**Comment by flareman** [comment]
Happy to be of help :) A thought, I can attest that thus command works for ComNav panels, but I am not sure about XGen and ZeroWire ones. Don't implement it blindly for all panel types, change the if statement to a switch and go from there depending on the panel type. That way, if someone else knows how the bypass works on other types other than ComNav, they can fork the file and write the necessary code.

**Comment by thanomichalis** [comment]
> Happy to be of help :) A thought, I can attest that thus command works for ComNav panels, but I am not sure about XGen and ZeroWire ones. Don't implement it blindly for all panel types, change the if statement to a switch and go from there depending on the panel type. That way, if someone else knows how the bypass works on other types other than ComNav, they can fork the file and write the necessary code.

Offcourse that is what i will do. That was the first attempt... so once i have instructions how to update the file in the container, i will do it properly and separate it.

**Comment by thanomichalis** [comment]
@flareman it is corrected already... thanks for the point in any case. :)

        elif self.vendor in (NX595EVendor.COMNAV):
            payload.update({
                'comm': 82,
                'data0': zone - 1,
            })
            
        else:  # self.vendor is NX595EVendor.{ZEROWIRE, XGEN}
            logger.error(
                 'Bypass not implemented for vendor {}'.format(self.vendor))
            return False

**Comment by chatziko** [comment]
> So how can i added into my HA?

What type of HA installation do you have?

**Comment by thanomichalis** [comment]
> > So how can i added into my HA?
> 
> What type of HA installation do you have?

On Raspberry Pi 4

**Comment by chatziko** [comment]
Ok I assume you run the Home Assistant OS in your pi. The following method is relatively easy, but involves having physical access to your pi with a keyboard/monitor to get a root terminal (cause when you ssh to HA, you connect to a different container than the one you want to modify).

1. Copy your `main.py` to HA under `/config/main.py` in any want you want (ssh, etc).
2. In the pi console (physical monitor/keyboard), type `login`, you will get a root prompt.
3. Run (careful with the colons/spaces)
    ```
    docker cp /mnt/data/supervisor/homeassistant/main.py homeassistant:/usr/local/lib/python3.10/site-packages/ultrasync
    ```
    This copies the `main.py` file to the appropriate location inside the `homeassistant` container.
4. Restart HA.

To revert the change, reinstall the package by running (again in the physical console)
```
docker exec -it homeassistant pip install ultrasync==0.9.5
```

**Comment by thanomichalis** [comment]
@chatziko thank you.

i tested it and it is working. So should i do so that to be included in the next update of the core?
Cause i presume in the next update, unless we put in the change, it will go back to the original main.py.

**Comment by chatziko** [comment]
Great news :smile: 

Just create a PR, it's a small change so @caronc will likely merge it and create a new release.

Modifying the extension's `manifest.json` is also an option (but a bit tricky).

Now that I think about it, [shell_commands](https://www.home-assistant.io/integrations/shell_command/) are also executed inside the container (never used them myself), so a shell_command with:
```
cp /config/main.py /usr/local/lib/python3.10/site-packages/ultrasync
```
should probably do the same thing, and you can automate it.

**Comment by thanomichalis** [comment]
> Great news 😄
> 
> Just create a PR, it's a small change so @caronc will likely merge it and create a new release.
> 
> Modifying the extension's `manifest.json` is also an option (but a bit tricky).
> 
> Now that I think about it, [shell_commands](https://www.home-assistant.io/integrations/shell_command/) are also executed inside the container (never used them myself), so a shell_command with:
> 
> ```
> cp /config/main.py /usr/local/lib/python3.10/site-packages/ultrasync
> ```
> 
> should probably do the same thing, and you can automate it.

OK... this week Ferrari submitted a patent filing for jet thrusters in their cars... so i think you have them already... slow down! 😄 
I am not that familiar with what you are saying. To be honest, chatGPT helped me to find the solution, by giving me the right direction where to look in the code!!! 

So i will open the PR and do it that way. 😃
