### ISSUE TITLE
Update for Comnav

### ISSUE THREAD

**Issue by thanomichalis** [caronc/ha-ultrasync#25]
Hi @caronc, any idea when the update will be available? I download it on a new installation, and it seems that it still installs the previous main.py file.

**Comment by caronc** [comment]
I published a release last week. What new changes are you looking for that appear missing?

**Comment by thanomichalis** [comment]
When i do a fresh install from hacs, it was suppose to use the updated main.py file that both tsotsos and myself have made changes. However it does not use the new one but the old one.
When calling the state of a zone for example, the can_bypass has null value, but based on what is in the code, it should give a value of true or false.
Here the file you have is correct. When installing the integration it is not.

**Comment by raj007manda** [comment]
Yes, HA/HACS showing 2 versions, please have a look:
![image](https://user-images.githubusercontent.com/56060815/229411058-8c4a4cbc-0103-4e0f-942a-3f0665acc64c.png)

**Comment by thanomichalis** [comment]
Check can_bypass state attribute. It is null.
Based on the code inside the main.py, it was suppose to be true or false based on if the zone is ready to be bypassed or not.

![image](https://user-images.githubusercontent.com/113099585/229746631-b636cc76-9293-47cd-8d14-0dd6edf2046a.png)

**Comment by thanomichalis** [comment]
Hello @caronc ,

Any update on the issue?

**Comment by caronc** [comment]
I'll try to look at this tomorrow if i can

**Comment by thanomichalis** [comment]
When trying to install the released version 1.0.0, in the manifest says to take the 0.9.5 ultrasync version.
When trying to install the main,  in the manifest says to take the 0.9.6 ultrasync version, however the main.py file of the 0.9.6 version, seems to be incorrect, and obviously, the HA says that a newer version of the integration exists.

**Comment by thanomichalis** [comment]
Solved in v1.0.3 HA
