### ISSUE TITLE
Version 1.0.4 Setup Failed

### ISSUE THREAD

**Issue by phyco1991** [caronc/ha-ultrasync#27]
Since upgrading the integration to the latest version in HACS the integration will no longer startup. The errors provided in the Home Assistant logs are below. I've tried removing/re-installing it in different variations of depth but don't seem to be able to get it working.

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 8:50:16 PM (3 occurrences)
Last logged: 8:50:30 PM
Unable to install package ultrasync==0.9.9: ERROR: Could not find a version that satisfies the requirement ultrasync==0.9.9 (from versions: 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8) ERROR: No matching distribution found for ultrasync==0.9.9 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:209
First occurred: 8:50:31 PM (1 occurrences)
Last logged: 8:50:31 PM
Setup failed for custom integration ultrasync: Requirements for ultrasync not found: ['ultrasync==0.9.9'].

**Comment by caronc** [comment]
Try again; i think i fixed this.

Sorry about that.

**Comment by phyco1991** [comment]
That appears to have fixed it, thanks!
