### ISSUE TITLE
Core - 2024.3.0b5 breaks UltraSync integration

### ISSUE THREAD

**Issue by smeee-again** [caronc/ha-ultrasync#33]
It appears that in the upcoming March release, this integration will stop working.  If I install the February release, the integration works again.  So something in the upcoming release is going to break this integration.

I have a dedicated "Dev" system that is similar to my production system, so the "Dev" system gets the beta updates.

**Comment by thanomichalis** [comment]
Same with mine.

However it is only the zone sensors that are unavailable. The area sensor is available, and i can arm/disarm the alarm.

**Comment by caronc** [comment]
I would advise not to upgrade to the newer release then. I welcome any pull requests to help resolve the new structure HA has implemented.

**Comment by smeee-again** [comment]
I looked through the release notes and not sure exactly what change has broken this.

This is why I have a Dev system though, so I know what it coming.

**Comment by thanomichalis** [comment]
Any progress on the issue now that HA released the 2024.3 ?

**Comment by smeee-again** [comment]
I'm not even sure what change they made has broken this.  With that said, it is possible that what they broke was an accident and .1 or even .2 could resolve it.

There were a lot of changes that involved using this:
async_update_entry
As well as other async changes.

**Comment by jxmagnus** [comment]
Yes Im interested as well.Its broken for me too on 2024.3

**Comment by chatziko** [comment]
Same thing here, I ll try to have a look if I find the time.

**Comment by caronc** [comment]
See my comment [here](https://community.home-assistant.io/t/interlogix-ultrasync/51464/241?u=l2g).  I'm definitely open to PR's right but won't have time to take a dive into this anytime soon.  I'm sorry :slightly_frowning_face:

**Comment by stefdewilde** [comment]
Is this change causing the failure for the sensors:

https://developers.home-assistant.io/blog/2024/02/12/async_update_entry/

**Comment by chatziko** [comment]
Looks like it was an issue with code running in an executor thread. I submitted a PR (#34 ), if anyone wants to test it grab the `custom_components/ultrasync` dir from [here](https://github.com/chatziko/ha-ultrasync/tree/fix-2024.3).

**Comment by smeee-again** [comment]
I'm going to close this issue since the changes from Chatziko also resolved the issue for me.

Thank you.
