### ISSUE TITLE
Ultrasync not showing up in integrations

### ISSUE THREAD

**Issue by jxmagnus** [caronc/ha-ultrasync#6]
Hi

I installed the Ultrasync beta in HACS as per the instructions and ive restarted my home assistant but it doesnt show up in my integrations page no matter what.Ive given this a couple of tries and also tried manually installing it from your repository.Any idea what might be wrong?

**Comment by caronc** [comment]
Hmm, is anything showing up in your HA logs that might help?

Do you have access to the command prompt to verify it installed okay? It might be a glitch on HACS and it only installed part of it. You could try removing it and re-adding it (you'll need to restart HA too so it can read in the new Python files).

**Comment by jxmagnus** [comment]
Thanks for the quick reply.I tried uninstalling and reinstalling it as suggested and it seems to have done the trick.Looks like it was an issue with HACS.
