### ISSUE TITLE
depricated error in log 

### ISSUE THREAD

**Issue by stefdewilde** [caronc/ha-ultrasync#8]
This error pops up in the logs:

Logger: ultrasync
Source: /usr/local/lib/python3.8/site-packages/ultrasync/main.py:435
First occurred: January 27, 2021, 9:01:50 PM (10 occurrences)
Last logged: January 27, 2021, 9:38:30 PM

set() is being depricated and replaced with set_alarm()

**Comment by caronc** [comment]
This issue should be resolved now in the latest push I made to HACS. :slightly_smiling_face:
